apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: qa-dev-role-binding
subjects:
- kind: Group
  name: qa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: qa-dev-role
  apiGroup: rbac.authorization.k8s.io
