apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: staging
  name: qa-staging-role-binding
subjects:
- kind: Group
  name: qa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: qa-staging-role
  apiGroup: rbac.authorization.k8s.io
